#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const year = '2019';
const baseDirPath = path.join(__dirname, '..');
const dirNames = fs.readdirSync(baseDirPath);

dirNames.forEach(dirName => {
  const updatedDirName = dirName.length === 2 ? dirName : '0' + dirName;
  if (dirName !== updatedDirName) {
    fs.renameSync(
      path.join(baseDirPath, dirName),
      path.join(baseDirPath, updatedDirName)
    );
  }
});
